export const VALIDATE_REQUIRE = 'VALIDATE_REQUIRE';
export const VALIDATE_MINLENGTH = 'VALIDATE_MINLENGTH';
export const VALIDATE_MAXLENGTH = 'VALIDATE_MAXLENGTH';
export const VALIDATE_MIN = 'VALIDATE_MIN';
export const VALIDATE_MAX = 'VALIDATE_MAX';
export const VALIDATE_EMAIL = 'VALIDATE_EMAIL';
export const VALIDATE_FILE = 'VALIDATE_FILE';
